const teamFlags: Record<string, string> = {
  "Africa do Sul": "🇿🇦",
  "África do Sul": "🇿🇦",
  Alemanha: "🇩🇪",
  Argentina: "🇦🇷",
  Argélia: "🇩🇿",
  Austrália: "🇦🇺",
  Brasil: "🇧🇷",
  Bélgica: "🇧🇪",
  Bósnia: "🇧🇦",
  "Bósnia e Herzegovina": "🇧🇦",
  "Cabo Verde": "🇨🇻",
  Canadá: "🇨🇦",
  Colômbia: "🇨🇴",
  Congo: "🇨🇩",
  "RD Congo": "🇨🇩",
  "Cost. do Marf.": "🇨🇮",
  "Costa do Marfim": "🇨🇮",
  Croácia: "🇭🇷",
  Egito: "🇪🇬",
  Equador: "🇪🇨",
  Espanha: "🇪🇸",
  "Estados Unidos": "🇺🇸",
  França: "🇫🇷",
  Gana: "🇬🇭",
  Holanda: "🇳🇱",
  "Países Baixos": "🇳🇱",
  Inglaterra: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Japão: "🇯🇵",
  Marrocos: "🇲🇦",
  México: "🇲🇽",
  Noruega: "🇳🇴",
  Paraguai: "🇵🇾",
  Portugal: "🇵🇹",
  Senegal: "🇸🇳",
  Suécia: "🇸🇪",
  Suíça: "🇨🇭",
  Áustria: "🇦🇹",
};

export function flagForTeam(team: string | null | undefined) {
  if (!team) return null;
  return teamFlags[team] ?? null;
}
